name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 10.15.3
        uses: actions/setup-node@master
        with:
          version: 10.15.3

      - name: Run a one-line script
        run: cd armstrong-react && npm i && npm run build

      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: armstrong-react/dist
